alpha: 0.8
beta: 1.0
gamma: 0.5
delta: 0.5
max_linear_acceleration: 2.0
max_angular_acceleration: 1.0
min_linear_velocity: -1.0
max_linear_velocity: 1.0
min_angular_velocity: -1.5
max_angular_velocity: 1.5
time_trajectory: 0.3
trajectory_sample: 2
velocity_sample: 7
sample_time: 0.1
